# chimera/config/planner/hybrid_planner.yaml
# HYBRID PLANNER VERSION 5.3 - Enhanced Scoring System (Version 5 + Novel Metrics)


hybrid_planner:
  _target_: chimera.planner.hybrid_planner.HybridPlanner
  _convert_: 'all'

  # PDM Planner configuration
  pdm_planner:
    _target_: tuplan_garage.planning.simulation.planner.pdm_planner.pdm_closed_planner.PDMClosedPlanner
    _convert_: 'all'
    trajectory_sampling:
      _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
      _convert_: 'all'
      num_poses: 80
      interval_length: 0.1
    proposal_sampling:
      _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
      _convert_: 'all'
      num_poses: 40
      interval_length: 0.1
    idm_policies:
      _target_: tuplan_garage.planning.simulation.planner.pdm_planner.proposal.batch_idm_policy.BatchIDMPolicy
      _convert_: 'all'
      speed_limit_fraction: [0.2, 0.4, 0.6, 0.8, 1.0]
      fallback_target_velocity: 15.0
      min_gap_to_lead_agent: 1.0
      headway_time: 1.5
      accel_max: 1.5
      decel_max: 3.0
    lateral_offsets: [-1.0, 0.0, 1.0]
    map_radius: 50.0

  # Diffusion Planner configuration
  diffusion_planner:
    _target_: diffusion_planner.planner.planner.DiffusionPlanner
    _convert_: 'all'
    config:
      _target_: diffusion_planner.utils.config.Config
      _convert_: 'all'
      args_file: ${oc.env:HOME}/chimera/diffusion_planner/checkpoints/args.json
      guidance_fn: null
    ckpt_path: ${oc.env:HOME}/chimera/diffusion_planner/checkpoints/model.pth
    past_trajectory_sampling:
      _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
      _convert_: 'all'
      num_poses: 20
      time_horizon: 2.0
    future_trajectory_sampling:
      _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
      _convert_: 'all'
      num_poses: 80
      time_horizon: 8.0
    device: cpu

  # Hybrid planner specific settings
  pdm_frequency: 10.0
  diffusion_frequency: 2.0
  
  # Enable scenario detection
  enable_scenario_detection: true
  
  # Conservative Oracle DDM configuration - KEEPING ALL V5 PARAMETERS
  leaky_ddm_config:
    # CONSERVATIVE MEMORY - don't forget what's working
    alpha: 0.7  # Higher memory to avoid erratic switches
    
    # CONSERVATIVE THRESHOLDS - require strong evidence
    theta_upper: 0.4   # Higher threshold
    theta_lower: -0.4  # Symmetric
    
    # BALANCED WEIGHTS
    scenario_weight: 0.6   # Scenario important but not overwhelming
    score_weight: 0.4      # Score validation important
    
    # HIGH CONFIDENCE REQUIRED
    min_confidence: 0.6    # Higher minimum
    high_confidence: 0.85  # Very high for override
    
    # Conservative override
    override_threshold: 0.4  # 40% win rate difference for override
    
    # SAFETY FIRST
    min_switch_interval: 3   # More cycles between switches
    min_score_threshold: 0.0 # Accept any score (don't reject trajectories)
    score_difference_threshold: 0.05 # Lower threshold for score differences
    
    # VALIDATION
    require_score_validation: true  # Must have good scores to switch
    fallback_to_pdm: true          # PDM as safe default
    
    # VERSION 6 ADDITIONS - ONLY ADDING NEW PARAMETERS
    # Enhanced metrics weight (new parameter)
    enhanced_metrics_weight: 0.6   # Weight for novel metrics in decision making
    
    # Safety fallback threshold (new parameter for debugging)
    # If both planners score below this threshold, PDM is selected UNLESS enhanced metrics override
    # Set to 0.0 to effectively disable safety fallback (for debugging only!)
    # Set to smaller values (e.g., 0.001) if both planners consistently score very low
    safety_fallback_threshold: 0.01  # Both scores must be below this to trigger safety fallback
    
    # Enhanced metric override gap (new parameter)
    # If enhanced metrics differ by more than this amount, they can override safety fallback
    # This allows the better-performing planner to be selected even with low base scores
    enhanced_metric_override_gap: 0.15  # Minimum gap in enhanced metrics to override safety fallback
    
    # Enhanced metric preferences by scenario (new parameter)
    metric_preferences:
      changing_lane:
        trajectory_efficiency: 0.3
        maneuver_preparedness: 0.4
        social_compliance: 0.3
      
      traversing_pickup_dropoff:
        spatial_utilization: 0.5
        trajectory_consistency: 0.3
        social_compliance: 0.2
      
      high_magnitude_speed:
        trajectory_efficiency: 0.4
        trajectory_consistency: 0.4
        social_compliance: 0.2
      
      starting_left_turn:
        maneuver_preparedness: 0.4
        spatial_utilization: 0.3
        trajectory_consistency: 0.3
      
      following_lane_with_lead:
        social_compliance: 0.5
        trajectory_consistency: 0.3
        trajectory_efficiency: 0.2
      
      low_magnitude_speed:
        spatial_utilization: 0.5
        trajectory_consistency: 0.3
        trajectory_efficiency: 0.2
      
      starting_straight_traffic_light_intersection_traversal:
        maneuver_preparedness: 0.4
        social_compliance: 0.3
        trajectory_efficiency: 0.3
      
      high_lateral_acceleration:
        trajectory_efficiency: 0.3
        spatial_utilization: 0.4
        trajectory_consistency: 0.3
      
      starting_right_turn:
        maneuver_preparedness: 0.4
        spatial_utilization: 0.3
        trajectory_consistency: 0.3
      
      stationary_in_traffic:
        social_compliance: 0.6
        trajectory_consistency: 0.4
        trajectory_efficiency: 0.0
      
      stopping_with_lead:
        social_compliance: 0.5
        trajectory_consistency: 0.3
        spatial_utilization: 0.2
      
      waiting_for_pedestrian_to_cross:
        social_compliance: 0.4
        trajectory_consistency: 0.4
        spatial_utilization: 0.2
      
      behind_long_vehicle:
        social_compliance: 0.5
        trajectory_consistency: 0.3
        maneuver_preparedness: 0.2
      
      near_multiple_vehicles:
        social_compliance: 0.4
        spatial_utilization: 0.3
        trajectory_consistency: 0.3